# Use root/example user/password credentials
version: '3.7'

services:
  php:
    container_name: php-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8500:80
    volumes:
      - ./src:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sam
      - MYSQL_DATABASE=appsama
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=db
    ports:
      - "8082:3306"

  phpmyadmin:
    image: samakunchan/phpmyadmin
    container_name: phpmyadmin-sama
    ports:
      - 8100:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=appsama
      - UPLOAD_LIMIT='300M'
    depends_on:
      - db

volumes:
  mysql-data:
